# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or create!d alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create!(name: "Luke", movie: movies.first)

Product.destroy_all
User.destroy_all

#prices: 1-9 = $, 10-20 = $$, 20+ = $$$


#US Cleansers
cetaphilCleanser = Product.create!(name: "Gentle Skin Cleanser", brand: "Cetaphil", country: "United States", type_of_product: "cleanser", ingredients: "water, cetyl alcohol, propylene glycol, sodium lauryl sulfate, stearyl alcohol", what_its_treating: "all skin types, including sensitive skin", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$", image: "https://media.allure.com/photos/59023bd57da179416ac6b43c/master/pass/allure-rca-2017-cetaphil-cleanser-review.jpg")
ceraveCleanser = Product.create!(name: "Renewing SA Cleanser", brand: "CeraVe", country: "United States", type_of_product: "cleanser", ingredients: "water, cocamidopropyl hydroxysultane, glycerin, sodium lauroyl sarcosinate, niacinamide", what_its_treating: "rough skin", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$$", image: "https://images.heb.com/is/image/HEBGrocery/001929382")
paulaCleanser = Product.create!(name: "Oil-Reducing Cleanser", brand: "Paula's Choice", country: "United States", type_of_product: "cleanser", ingredients: "water, sodium cocoyl isethionate, sodium lauroamphoacetate, stearic acid, glycerin", what_its_treating: "excess oil", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$$", image: "https://m.media-amazon.com/images/I/718PZc1o2rL.jpg")
neutroCleanser = Product.create!(name: "Hydro Boost Hydrating Cleansing Gel with Hyaluronic Acid, Fragrance Free", brand: "Neutrogena", country: "United States", type_of_product: "cleanser", ingredients: "water, glycerin, cocamidopropyl hydroxysultaine, sodium cocoyl isethionate, sodium chloride", what_its_treating: "hydration", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$", image: "https://ntg-catalog.imgix.net/products/6810272/6810272_alt_1.jpg?w=1200&h=1443&sfrm=jpg&fit=crop")
youthCleanser = Product.create!(name: "Superfood Cleanser", brand: "Youth to the People", country: "United States", type_of_product: "cleanser", ingredients: "water, cocamidopropyl hydroxysultaine, sodium cocoyl glutamate, sorbeth-230 tetraoleate, polysorbate 20", what_its_treating: "pores, dullness, & blemishes", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$$$", image: "https://media.kohlsimg.com/is/image/kohls/5077701?wid=600&hei=600&op_sharpen=1") 


#Korea Cleansers
cosrxCleanser = Product.create!(name: "Low pH Good Morning Gel Cleanser", brand: "COSRX", country: "South Korea", type_of_product: "cleanser", ingredients: "water, cocamidopropyl betaine, sodium lauroyl methyl isethionate, sodium chloride, polysorbate 20", what_its_treating: "dry, dull & sensitive skin, uneven texture", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$", image: "https://m.media-amazon.com/images/I/61UcS1QVdFS.jpg")
someCleanser = Product.create!(name: "AHA-BHA-PHA 30 Days Miracle Acne Clear Foam", brand: "SOME BY MI", country: "South Korea", type_of_product: "cleanser", ingredients: "water, glycerin, centella asiatica extract, palmitic acid, stearic acid", what_its_treating: "acne, oily skin, skin texture", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$$", image: "https://cdn.shopify.com/s/files/1/1165/6918/products/somebymi-3A-30-days-miracle-ac-clear-foam-main_1024x1024_1345b811-9a1a-4ac7-aa84-ed017c444ef0_2000x.webp?v=1649074964")
kraveCleanser = Product.create!(name: "Matcha Hemp Hydrating Cleanser", brand: "KRAVEBEAUTY", country: "South Korea", type_of_product: "cleanser", ingredients: "camellia sinesis leaf water, water, glycerin, dipropylene glycol, coco-betaine", what_its_treating: "all skin types, including sensitive skin; hydration", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$$", image: "https://i5.walmartimages.com/asr/bf449856-2309-4c71-91ab-3d777f83453c.df8df6b6bbe11c8109ebce61199dc18f.jpeg")
innisCleanser = Product.create!(name: "Blueberry Rebalancing Cleanser", brand: "innisfree", country: "South Korea", type_of_product: "cleanser", ingredients: "water, glycerin, sodium cocoyl isethionate, diglycerin, hydroxypropyl starch phosphate", what_its_treating: "hydration & unbalanced skin", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$", image: "https://cdn.shopify.com/s/files/1/0111/9309/0106/products/innisfree-blueberry-rebalancing-5.5-cleanser-200ml-texture-oo35mm_800x.jpg?v=1658255617")
joseonCleanser = Product.create!(name: "Green Plum Refreshing Cleanser", brand: "Beauty of Joseon", country: "South Korea", type_of_product: "cleanser", ingredients: "water, prunus mume fruit water, cocamidopropyl hydroxysultaine, phaseolus radiatus seed extract, sodium cocoyl isethionate", what_its_treating: "natural skin barrier; hydration", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$$", image: "http://cdn.shopify.com/s/files/1/0558/4135/7989/products/0O8A9381.jpg?v=1653271867")


#Japan Cleansers 
shiseidoCleanser = Product.create!(name: "Clarifying Cleansing Foam", brand: "Shiseido", country: "Japan", type_of_product: "cleanser", ingredients: "water, stearic acid, PEG-8, myristic acid, glycerin", what_its_treating: "moisture, radiance, all skin types", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$$$", image: "https://shiseido.ipscdn.net/sa2/dw/image/v2/BBSK_PRD/on/demandware.static/-/Sites-itemmaster_shiseido/default/dw5f20c8bf/images/2022/July/Top25/0730852145290_8.jpg?sw=540&sh=540&sm=fit")
hadaCleanser = Product.create!(name: "Goku-jyun Foaming Face Wash", brand: "Hada Labo", country: "Japan", type_of_product: "cleanser", ingredients: "water, PEG-8, butylene glycol, polyglyceryl-10 laurate, tea-cocoyl alaninate", what_its_treating: "moisture for sensitive skin", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$", image: "https://m.media-amazon.com/images/I/51lwy69v66S.jpg")
rosetteCleanser = Product.create!(name: "Sea Mud Kaidei Smooth Cleansing Paste", brand: "Rosette", country: "Japan", type_of_product: "cleanser", ingredients: "water, myristic acid K (vegetable soap), stearic acid (skin protection agent), glycerin (humectant), stearic acid K (vegetable soap)", what_its_treating: "oily and combination skin", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$", image: "https://cdn.shopify.com/s/files/1/0046/3211/7351/products/rosette-cleansers-rosette-sea-mud-kaidei-smooth-cleansing-paste-12319607455847_1200x.jpg?v=1592867299")
bioreCleanser = Product.create!(name: "Deep Pore Charcoal Cleanser", brand: "Bioré", country: "Japan", type_of_product: "cleanser", ingredients: "water, glycerin, sodium laureth sulfate, cocamidopropyl betaine, sorbitol", what_its_treating: "clogged pores & skin impurities", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$", image: "https://m.media-amazon.com/images/I/618Ba5WRtWL.jpg")
tatchaCleanser = Product.create!(name: "The Rice Wash", brand: "Tatcha", country: "Japan", type_of_product: "cleanser", ingredients: "water, microcrystalline cellulose, propanediol, sodium cocoyl glutamate, glycerin", what_its_treating: "hydration & unbalanced skin", directions: "Use as first step in skincare routine. Gently rub the cleanser over your whole face using hands and water. Rinse off face using water and pat dry; Follow after with other skincare products.", price: "$$$", image: "https://glamorable.com/wp-content/uploads/2020/08/tatcha-the-rice-wash-review-04.jpg")


#US Serums
skinceuticalsSerum = Product.create!(name: "Phloretin CF With Ferulic Acid", brand: "Skinceuticals", country: "United States", type_of_product: "serum", ingredients: "water, dipropylene glycol, alcohol denat., ascorbic acid, butylene glycol", what_its_treating: "discoloration & environmental protection", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM. Apply four to five drops to face and neck. Follow after with other skincare products. Use sunscreen with this product.", price: "$$$", image: "https://static.thcdn.com/images/large/original//productimg/1600/1600/11289626-1934892771763618.jpg")
paulaSerum = Product.create!(name: "Intensive Wrinkle-Repair Retinol Serum", brand: "Paula's Choice", country: "United States", type_of_product: "serum", ingredients: "cyclopentasiloxane, dimethiconol, neopentyl glycol diheptanoate, dicprylyl carbonate, caprylic/capric treiglyceride", what_its_treating: "appearance of wrinkles, skin firmness, & uneven skin tone", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply a few drops to face and neck. Follow after with other skincare products. In the AM, use with sunscreen of atleast 30 SPF.", price: "$$$", image: "https://www.paulaschoice.com/dw/image/v2/BBNX_PRD/on/demandware.static/-/Sites-pc-catalog/default/dwf0118f8a/images/views/resist-intensive-wrinkle-repair-retinol-serum-7710-L-lifestyle1.png?sw=360&sfrm=jpg")
glossierSerum = Product.create!(name: "Super Glow", brand: "Glossier", country: "United States", type_of_product: "serum", ingredients: "water, magnesium ascorbyl phosphate, propanediol, dimethicone, glycerl stearate SE", what_its_treating: "appearance of dark spots, hydration, & sensitive skin", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply three to four drops to face and neck. Follow after with other skincare products.", price: "$$$", image: "https://cdn.shopify.com/s/files/1/0627/9164/7477/products/SuperGlow_0_Global_03_750x.jpg?v=1656604715")
dermalogicaSerum = Product.create!(name: "Circular Hydration Serum with Hyaluronic Acid", brand: "dermalogica", country: "United States", type_of_product: "serum", ingredients: "water, PEG-8, glycerin, methylpropanediol, PPG-24-glycereth-24", what_its_treating: "dryness, dehydration, wrinkles, & firmness", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and PM. Apply a few drops to face and neck. Follow after with other skincare products.", price: "$$$", image: "https://cdn.shopify.com/s/files/1/0420/7683/1896/products/Launch-Site_Circular-Hydration-Serum_PDPImage-05_1000x1000.jpg?v=1660084890")
ceraveSerum = Product.create!(name: "Resurfacing Retinol Serum", brand: "CeraVe", country: "United States", type_of_product: "serum", ingredients: "water, propanediol, dimethicone, cetearyl ethylhexanoate, niacinamide", what_its_treating: "post-acne scars & pores", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply a few drops to face and neck. Follow after with other skincare products. Apply sunscreen when using this serum.", price: "$$", image: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/serums/resurfacing-retinol-serum/cerave_resurfacing_retinol-serum-pump-700x875-v1.jpg?rev=f28399dcd0b443b38354ea09d13a06ab")

#Korea Serums
cosrxSerum = Product.create!(name: "Advanced Snail 96 Mucin Power Essence", brand: "COSRX", country: "South Korea", type_of_product: "serum", ingredients: "snail secretion filtrate, betaine, butylene glycol, 1,2-hexanediol, sodium polycrylate", what_its_treating: "dark spots, skin texture, anti-aging, & hydration", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply a few drops to face and neck. Follow after with other skincare products.", price: "$$$", image: "https://cdn.shopify.com/s/files/1/0249/1218/products/1.31-Soko-Glam-PDP-Image-COSRX-Advanced-Snail-96-Mucin-Power-Essence-Product-Lifestyle_860x.jpg?v=1644510538")
haruSerum = Product.create!(name: "Black Rice Hyaluronic Anti-Wrinkle Serum", brand: "haruharu wonder", country: "South Korea", type_of_product: "serum", ingredients: "deionized water, glycerin, lecithin, caprylic/capric triglyceride, camellia seed oil", what_its_treating: "wrinkles, skin elasticity & firmness", directions: "Use as a step in skincare routine after toner and before moisturizer. Shake before using and apply where wrinkles are apparent. Follow after with other skincare products.", price: "$$$", image: "https://cdn.shopify.com/s/files/1/0249/1218/products/9.15-Soko-Glam-PDP-Image-Haruharu-Wonder-Black-Rice-Hyaluronic-Anti-Wrinkle-Serum-Korean-Skincare-Product-Lifestyle_860x.jpg?v=1663774624")
peachSerum = Product.create!(name: "Glass Skin Refining Serum", brand: "Peach & Lily", country: "South Korea", type_of_product: "serum", ingredients: "water, propanediol, butylene glycol, niacinamide, 1,2-hexanediol", what_its_treating: "hydration, sensitive skin, & dullness", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply a few drops to face and neck. Follow after with other skincare products.", price: "$$$", image: "https://media.allure.com/photos/61254662c806bdb6be9d8bbe/1:1/w_800,h_800,c_limit/peach%20and%20lily%20resurfacing%20serum%20jumbo%20size.jpg")
joseonSerum = Product.create!(name: "Glow Serum", brand: "Beauty of Joseon", country: "South Korea", type_of_product: "serum", ingredients: "propolis extract, dipropylene glycol, glycerin, butylene glycol, water", what_its_treating: "glow, flare ups, & complexion", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and PM. Apply two to three drops to face and neck. Follow after with other skincare products.", price: "$$", image: "https://m.media-amazon.com/images/I/41zON+1vX4L.jpg")
puritoSerum = Product.create!(name: "Centella Green Level Buffet Serum", brand: "Purito", country: "South Korea", type_of_product: "serum", ingredients: "centella asiatica extract (strengthens skin barrier), water, dipropylene glycol, glycerin, niacinamide", what_its_treating: "inflammation, radiance, wrinkles, & skin elasticity", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply one to two drops to face and neck. Follow after with other skincare products.", price: "$$", image: "http://cdn.shopify.com/s/files/1/0325/8223/8252/products/ATL0028_tm.jpg?v=1596396175")

#Japan Serums
hadaSerum = Product.create!(name: "Goku-jyun Hyaluronic Serum", brand: "Hada Labo", country: "Japan", type_of_product: "serum", ingredients: "water, glycerin, butylene glycol, pentylene glycol, PPG-10 methyl glucose ether", what_its_treating: "hydration & moisture", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply two to three drops to face and neck. Follow after with other skincare products.", price: "$$", image: "https://img.makeupalley.com/2/6/2/8/3511325.PNG")
skiiSerum = Product.create!(name: "GenOptics Aura Essence Serum", brand: "SK-II", country: "Japan", type_of_product: "serum", ingredients: "water, galactomycese ferment filtrate, niacinamide, butylene glycol, triethylhexanoin", what_its_treating: "dark spots, dullness, uneven skintone & texture", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply a full dropper of serum to face and neck. Follow after with other skincare products.", price: "$$$", image: "https://www.sephora.com/productimages/sku/s1863208-main-zoom.jpg")
shiseidoSerum = Product.create!(name: "Power Infusing Serum", brand: "Shiseido", country: "Japan", type_of_product: "serum", ingredients: "water, SD alcohol 40-B, glycerin, butylene glycol, dimethicone", what_its_treating: "signs of aging & hydration", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and PM. Apply two pumps to face and neck. Follow after with other skincare products.", price: "$$$", image: "https://shiseido.ipscdn.net/sa2/dw/image/v2/BBSK_PRD/on/demandware.static/-/Sites-itemmaster_shiseido/default/dw49b20bba/images/2021/December/Ultimune/0730852172883_1.jpg?sw=540&sh=540&sm=fit")
albionSerum = Product.create!(name: "eclafutur d", brand: "Albion", country: "Japan", type_of_product: "serum", ingredients: "water, butylene glycol, glycerin, propylene glycol, alcohol", what_its_treating: "hydration & skin cell function", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply two to three pumps to face and neck. Follow after with other skincare products.", price: "$$$", image: "http://cdn.shopify.com/s/files/1/0103/2254/2651/products/AAIOUI-eclafutur_d_40ml_1200x630.jpg?v=1628531330")
kikuSerum = Product.create!(name: "Sake Skin Care Essence", brand: "Kikumasamune", country: "Japan", type_of_product: "serum", ingredients: "water, butylene glycol, glycosyl trehalose, hydrogenated starch hydrolysate, rice ferment filtrate (sake)", what_its_treating: "hydration & smoothness", directions: "Use as a step in skincare routine after toner and before moisturizer. Can use in the AM and/or PM. Apply two to three pumps to face and neck. Follow after with other skincare products.", price: "$$$", image: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/kks/kks80077/l/3.jpg")

#US Moisturizers
neutroMoisturizer = Product.create!(name: "Hydro Boost Water Gel", brand: "Neutrogena", country: "United States", type_of_product: "moisturizer", ingredients: "water, dimethicone, glycerin, dimethicone/vinyl dimethicone crosspolymer, phenoxyethanol", what_its_treating: "dry skin & hydration", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and PM. Apply to face and neck evenly. Follow after with other skincare products.", price: "$$$", image: "https://m.media-amazon.com/images/I/71Xw9oOvYyL.jpg")
ceraveMoisturizer = Product.create!(name: "AM Facial Moisturizing Lotion with Sunscreen", brand: "CeraVe", country: "United States", type_of_product: "moisturizer", ingredients: "homosalate, meradimate, octinoxate, octocrylene, zinc oxide", what_its_treating: "moisture, natural skin barrier, & protection against UV rays", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM. Apply to face and neck evenly. Follow after with other skincare products. Reapply every two hours", price: "$$", image: "https://i5.walmartimages.com/asr/89159725-c251-47ba-94e7-35ff6bbec59e.ec33ed3cd198706c2a5b4c0d743a53ee.jpeg")
firstMoisturizer = Product.create!(name: "Ultra Repair Cream Intense Hydration", brand: "First Aid Beauty", country: "United States", type_of_product: "moisturizer", ingredients: "colloidal oatmeal, water, stearic acid, glycerin, c12-15 alkyl benzoate", what_its_treating: "hydration & dry skin including eczema", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly. Follow after with other skincare products.", price: "$$$", image: "https://www.sephora.com/productimages/product/p248407-av-10-zoom.jpg")
cliniqueMoisturizer = Product.create!(name: "Dramatically Different Moisturizing Lotion", brand: "Clinique", country: "United States", type_of_product: "moisturizer", ingredients: "water, mineral oil, glycerin, petrolatum, stearic acid", what_its_treating: "skin's moisture barrier & hydration", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly. Follow after with other skincare products.", price: "$$$", image: "https://n.nordstrommedia.com/id/sr3/309d2411-fc05-4ce0-8418-89e412d58169.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196")
kiehlsMoisturizer = Product.create!(name: "Ultra Facial Cream with Squalane", brand: "Kiehl's", country: "United States", type_of_product: "moisturizer", ingredients: "water, glycerin, cyclohexasiloxane, squalane, bis-PEG-18 methyl ether dimethyl silane", what_its_treating: "all skin types including sensitive skin; skin's natural moisture barrier", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply a dime-sized amount to face and neck evenly. Follow after with other skincare products.", price: "$$$", image: "https://www.kiehls.com/dw/image/v2/AAFM_PRD/on/demandware.static/-/Sites-kiehls-master-catalog/default/dwdfe0eed7/nextgen/skin-care/face-moisturizers/ultra-facial/ultra-facial-cream/kiehls-face-cream-ultra-facial-cream-125ml-000-3605975028799-whip.jpg?sw=560&sh=465&sm=cut&sfrm=png&q=70")


#Korea Moisturizers
soonMoisturizer = Product.create!(name: "2x Barrier Intensive Cream", brand: "Soon Jung", country: "South Korea", type_of_product: "moisturizer", ingredients: "water, propanediol, pentaerythrityl, tetraethylhexanoate, caprylic/capric triglyceride", what_its_treating: "dry skin barrier & hydration", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly. Follow after with other skincare products.", price: "$$", image: "https://www.etude.com/int/en/media/catalog/product/cache/07b96aa9f5b70f577958b488444f8dd2/s/o/soonjung_2021_thumbnail_2x_barrier_cream.jpg")
laneigeMoisturizer = Product.create!(name: "Water Bank Moisture Cream", brand: "Laneige", country: "South Korea", type_of_product: "moisturizer", ingredients: "water, propanediol, glycerin, methyl trimethicone, phenyl trimethicone", what_its_treating: "skin's moisture barrier & complexion", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly. Follow after with other skincare products.", price: "$$$", image: "https://i.ebayimg.com/images/g/QhsAAOSwptxhXnsl/s-l500.jpg")
cosrxMoisturizer = Product.create!(name: "Oil-Free Ultra-Moisturizing Lotion with Birch Sap", brand: "COSRX", country: "South Korea", type_of_product: "moisturizer", ingredients: "betula platyphylla japonica juice, butylene glycol, glycerin, dimethicone, betaine", what_its_treating: "irritated skin, hydration, & all skin types", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly and tap it in for the product to full absorb. Follow after with other skincare products.", price: "$$$", image: "https://m.media-amazon.com/images/I/51jI1dL0+NL.jpg")
pyungMoisturizer = Product.create!(name: "Moisture Cream", brand: "Pyungkang Yul", country: "South Korea", type_of_product: "moisturizer", ingredients: "coptis chinensis root extract, butylene glycol, simmondsia chinensis (jojoba) seed oil, polyglyceryl-3 methylglucose distearate, cetyl ethylhexanoate", what_its_treating: "hydration & rough skin", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly and add a second layer to areas of concern. Follow after with other skincare products.", price: "$$$", image: "https://m.media-amazon.com/images/I/51uMe28Mm9L.jpg")
iunikMoisturizer = Product.create!(name: "Beta Glucan Daily Moisture Cream", brand: "iUNIK", country: "South Korea", type_of_product: "moisturizer", ingredients: "water, butylene glycol, glycerin, methyl trimethicone, centella asiatica extract", what_its_treating: "all skin types including dry skin; hydration", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly. Follow after with other skincare products.", price: "$$", image: "https://m.media-amazon.com/images/I/61MOVeiZaqL.jpg")

#Japan Moisturizer
shiseidoMoisturizer = Product.create!(name: "Hydrating Day Cream Broad Spectrum SPF 20", brand: "Shiseido", country: "Japan", type_of_product: "moisturizer", ingredients: "avobenzone, homosalate, octisalate, octocrylene, water", what_its_treating: "skin's moisture barrier, pores, & fine lines", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply two pearl-sized amounts to face and neck evenly. Follow after with other skincare products.", price: "$$$", image: "https://shiseido.ipscdn.net/sa2/dw/image/v2/BBSK_PRD/on/demandware.static/-/Sites-itemmaster_shiseido/default/dw85e2ebc7/images/2021/December/Essential%20Energy/0729238182851_1.jpg?sw=800&sh=800&sm=fit")
curelMoisturizer = Product.create!(name: "Intensive Moisture Facial Cream", brand: "Curél", country: "Japan", type_of_product: "moisturizer", ingredients: "water, glycerin, cetyl-PG hydroxyethyl palmitamide, cyclopentasiloxane, squalane", what_its_treating: "dry, sensitive skin & skin's natural barrier function", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply a grape-sized amount to face and neck evenly. Follow after with other skincare products.", price: "$$$", image: "https://m.media-amazon.com/images/I/718NJ5EpyRL.jpg")
mujiMoisturizer = Product.create!(name: "Moisturizing Milk", brand: "MUJI", country: "Japan", type_of_product: "moisturizer", ingredients: "water, dpg, glycerin, ethylhexyl palmitate, PEG-32", what_its_treating: "sensitive skin & hydration", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly. Follow after with other skincare products.", price: "$$", image: "https://img.muji.net/img/item/4547315258550_1260.jpg")
sanaMoisturizer = Product.create!(name: "Namerakahonpo Cream", brand: "SANA", country: "Japan", type_of_product: "moisturizer", ingredients: "water, glycerin, butylene glycol, alcohol, cyclopentasiloxane", what_its_treating: "pores & hydration", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly. Follow after with other skincare products.", price: "$$$", image: "https://img.makeupalley.com/thumb/h/350/1_1_8_1_3597436.jpg")
hadaMoisturizer = Product.create!(name: "Goku-jyun Hyaluronic Perfect Gel", brand: "Hada Labo", country: "Japan", type_of_product: "moisturizer", ingredients: "water, butylene glycol, hydroxyethyl urea, pentylene glycol, glycerin", what_its_treating: "firmness & moisture", directions: "Use as a step in skincare routine after serums and before sunscreen. Can use in the AM and/or PM. Apply to face and neck evenly. Follow after with other skincare products.", price: "$$$", image: "https://cdn.shopify.com/s/files/1/1969/5775/products/Rohto-Hada-Labo-Koi-Gokujyun-Perfect-Gel-100g-Japanese-Taste-2.jpg?v=1646061350")

#US Sunscreen
neutroSunscreen = Product.create!(name: "Ultra Sheer Dry-Touch Sunscreen Lotion Broad Spectrum SPF 70", brand: "Neutrogena", country: "United States", type_of_product: "sunscreen", ingredients: "water, butyloctyl salicylate, styrene/acrylates copolymer, silica, dimethicone", what_its_treating: "sun protection & anti-aging", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$", image: "https://ntg-catalog.imgix.net/products/6868770-MAIN-1221.jpg?w=720&h=866&sfrm=jpg&fit=crop")
cetaphilSunscreen = Product.create!(name: "Sheer Mineral Sunscreen Broad Spectrum SPF 50", brand: "Cetaphil", country: "United States", type_of_product: "sunscreen", ingredients: "titanium dioxide, zinc oxide, water, isohexadecane, butyloctyl salicylate", what_its_treating: "sun exposure, sensitive skin, & weak skin barrier", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$", image: "https://i5.walmartimages.com/asr/9c27cd25-0fe7-4844-b174-ea3e38b515d7.9db718e99fb1913fc4f3f632db7971ab.jpeg")
supergoopSunscreen = Product.create!(name: "Unseen Sunscreen SPF 40", brand: "Supergoop!", country: "United States", type_of_product: "sunscreen", ingredients: "avobenzone, homosalate, octisalate, octocrylene, isododecane", what_its_treating: "moisture & sun exposure", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$", image: "https://n.nordstrommedia.com/id/sr3/c590a6d9-4020-4d46-bee7-cdc50acaedfc.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196")
ceraveSunscreen = Product.create!(name: "Hydrating Mineral Sunscreen SPF 30 Face Lotion", brand: "CeraVe", country: "United States", type_of_product: "sunscreen", ingredients: "titanium dioxide, zinc oxide, water, glycerin, C12-15 alkyl benzoate", what_its_treating: "UV damage, sensitive skin, & skin barrier", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$", image: "https://target.scene7.com/is/image/Target/GUEST_469f304f-3178-45d0-8b96-deea1a11309d?wid=488&hei=488&fmt=pjpeg")
traderSunscreen = Product.create!(name: "Daily Facial Sunscreen SPF 40", brand: "Trader Joe's", country: "United States", type_of_product: "sunscreen", ingredients: "avobenzone, homosalate, octisalate, octocrylene,  isododecane", what_its_treating: "all skin types", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$", image: "https://www.traderjoes.com/content/dam/trjo/context-images/73568-daily-facial-sunscreen-pdp.jpg/jcr:content/renditions/cq5dam.web.1280.1280.jpeg")

#Korea Sunscreen
joseonSunscreen = Product.create!(name: "Rice Sun: Rice + Probiotics SPF50+ PA++++", brand: "Beauty of Joseon", country: "South Korea", type_of_product: "sunscreen", ingredients: "water, oryza sativa (rice) extract, dibutyl adipate, propanediol, diethylamino hydroxybenzoyl hexyl benzoate", what_its_treating: "skin's moisture & nourishment; hydration", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$", image: "http://cdn.shopify.com/s/files/1/0558/4135/7989/products/0O8A9467.jpg?v=1653271992")
cosrxSunscreen = Product.create!(name: "Aloe Soothing Sun Cream SPF50 PA+++", brand: "COSRX", country: "South Korea", type_of_product: "sunscreen", ingredients: "water, ethylhexyl methoxycinnamate, glycerin, propylene glycol, cyclopentasiloxane", what_its_treating: "dehydrated skin, no white cast, sun protection", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$", image: "https://m.media-amazon.com/images/I/41JGrbwwqDL.jpg")
farmerSunscreen = Product.create!(name: "Sun Project Water Sun Cream SPF50+ PA+++", brand: "Thank You Farmer", country: "South Korea", type_of_product: "sunscreen", ingredients: "water, ethylhexyl methoxycinnamate, homosalate, diethylamino hydroxybenzoyl hexyl benzoate, butylene glycol", what_its_treating: "UV rays, signs of aging, & hydration", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$$", image: "https://i.etsystatic.com/33221723/r/il/d4f669/3566557901/il_fullxfull.3566557901_dzd6.jpg")
misshaSunscreen = Product.create!(name: "All Around Safe Block Soft Finish Sun Milk SPF50+/PA+++", brand: "MISSHA", country: "South Korea", type_of_product: "sunscreen", ingredients: "helichrysum arenarium extract, cyclopentasiloxane, homosalate, silica, titanium dioxide (CI 77891)", what_its_treating: "sun protection, skin damage, & aging", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$$", image: "https://m.media-amazon.com/images/I/315hK3Z8U5L.jpg")
innisSunscreen = Product.create!(name: "Daily UV Defense Sunscreen", brand: "innisfree", country: "South Korea", type_of_product: "sunscreen", ingredients: "avobenzone, homosalate, octisalate, water, butylene glycol", what_its_treating: "hydration & UV damage", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$", image: "https://m.media-amazon.com/images/I/31GXrdz1ZdL._AC_SY1000_.jpg")

#Japan Sunscreen
canmakeSunscreen = Product.create!(name: "Mermaid Skin Gel UV SPF50+/PA++++", brand: "CANMAKE", country: "Japan", type_of_product: "sunscreen", ingredients: "water, ethylhexyl methoxycinnamate, butylene glycol, diethylamino hydroxybenzoyl hexyl benzoate, zinc oxide", what_its_treating: "skin brightening, hydration, & UV protection", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$", image: "https://cdn.shopify.com/s/files/1/0231/1294/1648/files/DSC_0492_1024x1024.jpg?v=1636029492")
bioreSunscreen = Product.create!(name: "Aqua Rich Watery Essence SPF50+ PA++++", brand: "Bioré", country: "Japan", type_of_product: "sunscreen", ingredients: "water, alcohol, ethylhexyl methoxycinnamate, ethylhexyl triazone, isopropyl palmitate", what_its_treating: "UV damage, dry skin, & hydration", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$", image: "https://cdn.shopify.com/s/files/1/1969/5775/products/Kao-Biore-UV-Aqua-Rich-Watery-Essence-SPF50-PA-50g-Japanese-Taste-2_aa5e13a9-b924-4445-9152-5041bf5fabf0.jpg?v=1628764145")
kaneboSunscreen = Product.create!(name: "Gel Sunscreen UV EX (Coral Reef Safe Sunscreen) SPF50+ PA++++", brand: "Kanebo Allie", country: "Japan", type_of_product: "sunscreen", ingredients: "water, zinc oxide (Ci 77947), alcohol, ethylhexyl methoxycinnamate 7.2%, triethylhexanoin", what_its_treating: "eco-friendly; hydration; sun and pollution protection", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$$", image: "http://cdn.shopify.com/s/files/1/1969/5775/products/Kanebo-Allie-Gel-Sunscreen-UV-EX-Coral-Reef-Safe-Sunscreen-SPF50-PA-90g-Japanese-Taste-2.jpg?crop=center&height=1200&v=1646131231&width=1200")
beSunscreen = Product.create!(name: "UV Milk", brand: "&be", country: "Japan", type_of_product: "sunscreen", ingredients: "water, caprylic/capric triglyceride, zinc oxide, dipropylene glycol, titanium dioxide", what_its_treating: "UV rays protection & skin tone", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$$", image: "https://cdn.shopify.com/s/files/1/1408/0624/products/pdt_03__1_b_650x.jpg?v=1649159981")
shiseidoSunscreen = Product.create!(name: "Ultimate Sun Protector Cream SPF 50+ Sunscreen", brand: "Shiseido", country: "Japan", type_of_product: "sunscreen", ingredients: "octisalate, octocrylene, titanium dioxide, zinc oxide, water", what_its_treating: "sun protection", directions: "Use as the last step in skincare routine after moisturizer. Use in the AM. Apply to face and neck evenly. Reapply every 2 hours.", price: "$$$", image: "https://www.sephora.com/productimages/sku/s2339943-main-zoom.jpg")

first = User.create!(username: "angels-skin", password:"hello1*")
second = User.create!(username: "skincera", password:"hello2*")
third = User.create!(username: "baby-skin", password:"hello3*")
fourth = User.create!(username: "face-up", password:"hello4*")

Review.create!(user_id: first.id, product_id: joseonSunscreen.id, rating: 9, changes_in_skin: "smoother skin texture, glow, & moisturized skin", duration: "3 months", positive: "light weight", negative: "feels like there is less product", repurchase: true)
Review.create!(user_id: second.id, product_id: cosrxSerum.id, rating: 8, changes_in_skin: "smoother skin texture, less dark spots & breakouts", duration: "1 year", positive: "very hydrating", negative: "took a long time to notice change in my skin", repurchase: true)
Review.create!(user_id: third.id, product_id: ceraveMoisturizer.id, rating: 6, changes_in_skin: "not many changes other than moisturized skin", duration: "5 months", positive: "sunscreen is included in moisturizer", negative: "feels pretty thick and there is a white cast", repurchase: false)
Review.create!(user_id: fourth.id, product_id: skiiSerum.id, rating: 4, changes_in_skin: "hydrated & glowing skin", duration: "4 months", positive: "feels luxurious", negative: "too expensive for what it does; can easily find dupes", repurchase: false)
Review.create!(user_id: second.id, product_id: kraveCleanser.id, rating: 7, changes_in_skin: "skin doesn't feel too dry or tight after using", duration: "3 months", positive: "includes natural ingredients", negative: "overhyped", repurchase: true)
Review.create!(user_id: first.id, product_id: hadaMoisturizer.id, rating: 8, changes_in_skin: "hydrated skin", duration: "8 months", positive: "light weight and very moisturizing", negative: "not accessible in all stores", repurchase: true)









